### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by DomiSparkz** [rumi-chan/Sakura#12]
Got an error pop up that says something along the lines of "failed to find pattern" followed by some random letters and numbers. I made sure to inject it after the arena was selected. What could be wrong? Im a newbie in these things :c

**Comment by rumi-chan** [comment]
> Got an error pop up that says something along the lines of "failed to find pattern" followed by some random letters and numbers. I made sure to inject it after the arena was selected. What could be wrong? Im a newbie in these things :c

i'll update soon

**Comment by DomiSparkz** [comment]
oh ;D thanks!! <3
