### ISSUE TITLE
13.22版本用不了

### ISSUE THREAD

**Issue by zjxj1314** [rumi-chan/Sakura#13]
请问更新了吗？还是说并不会更新了。

**Comment by zjxj1314** [comment]
我不会英语，麻烦您翻译一下

**Comment by zjxj1314** [comment]
抱歉，我不会英语，请您翻译一下

**Comment by rumi-chan** [comment]
work in progress

**Comment by BakaFT** [comment]
latest update working fine on tencent server now

刚更新的版本我试过了，国服能用
