### ISSUE TITLE
There's a malware?

### ISSUE THREAD

**Issue by kappacinno** [rumi-chan/Sakura#14]
I cannot download it. it says there's a virus. Is this safe or bannable?

**Comment by rumi-chan** [comment]
> I cannot download it. it says there's a virus. Is this safe or bannable?

![CF10125A-AEA0-4ACB-86C6-5E955E2B3FA4](https://github.com/rumi-chan/Sakura/assets/59478113/aff300e8-d12c-4fd7-9eaa-e609ddb1631b)

**Comment by rumi-chan** [comment]
>https://github.com/rumi-chan/Sakura#faqs
