### ISSUE TITLE
New bug on the HUD

### ISSUE THREAD

**Issue by Albystar** [rumi-chan/Sakura#16]
Im currently in patch 13.23, when i first selected a tactician on the HUD menu it went fine, but now every time i open the skinchanger i cant change it anymore also the menu doesnt show up anymore, pls fix tks

**Comment by rumi-chan** [comment]
> Im currently in patch 13.23, when i first selected a tactician on the HUD menu it went fine, but now every time i open the skinchanger i cant change it anymore also the menu doesnt show up anymore, pls fix tks

Can you send me your config file?
It's in Documents/Sakura

**Comment by d1fwn** [comment]
Hi @rumi-chan  you said you will post a new version in 2 days, but it isn't  sorry to be mean, or annoying ,but I really love your work and really love to play with different pets on tft
