### ISSUE TITLE
Does this mod have the Chibi from the China server? 

### ISSUE THREAD

**Issue by tunh-dev1** [rumi-chan/Sakura#26]
@rumi-chan

**Comment by rumi-chan** [comment]
> @rumi-chan

TFT - yes
Golden Spatula - no

> @rumi-chan

**Comment by tunh-dev1** [comment]
can i have the link to join your discord? 
the link you posted was expired.

**Comment by rumi-chan** [comment]
i closed that server
now only a few of my friends are there
