### ISSUE TITLE
About China Server

### ISSUE THREAD

**Issue by GB756980** [rumi-chan/Sakura#8]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/544

修改R3nzSkin.dll为hid.dll，并将其复制到LOL的Game目录下，即可使用！
Sakura是否也可以？如果可以，修改成什么名字呢？

Change R3nzSkin.dll to hid.dll and copy it to LOL's Game directory and it's ready to use!
Can Sakura do the same? If so, what name should I change it to?

**Comment by rumi-chan** [comment]
> [R3nzTheCodeGOD/R3nzSkin#544](https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/544)
> 
> 修改R3nzSkin.dll为hid.dll，并将其复制到LOL的Game目录下，即可使用！ Sakura是否也可以？如果可以，修改成什么名字呢？
> 
> Change R3nzSkin.dll to hid.dll and copy it to LOL's Game directory and it's ready to use! Can Sakura do the same? If so, what name should I change it to?

Yes, you can do the same method with Sakura. Rename it to hid.dll and put it to Game directory.
But I don't recommend this injection method because I don't know how dangerous it is.

**Comment by GB756980** [comment]
R3nzSkin.dll已经更名成hid.dll，Sakura无法再更名成hid.dll。显而易见，这样会让名字重复。
没有办法能让这两个软件同时运作，对吗？

R3nzSkin.dll has been renamed to hid.dll, Sakura cannot be renamed to hid.dll again. Obviously, this makes the name duplicate.
There's no way to make these two programs work at the same time, is there?

**Comment by rumi-chan** [comment]
> R3nzSkin.dll已经更名成hid.dll，Sakura无法再更名成hid.dll。显而易见，这样会让名字重复。 没有办法能让这两个软件同时运作，对吗？
> 
> R3nzSkin.dll has been renamed to hid.dll, Sakura cannot be renamed to hid.dll again. Obviously, this makes the name duplicate. There's no way to make these two programs work at the same time, is there?

You can't inject 2 dll files at the same time that way. (as far as I know)
But why would you want to inject both?

**Comment by GB756980** [comment]
因为我需要将两个文件都改名成hid.dll，并将它复制到Game文件夹，这是一件只需要做一次的事情。因为和其他服务器不一样，需要注入器才可以。

Because I need to rename both files to hid.dll and copy it to the Game folder, which is something I only need to do once. Because unlike other servers, you need an injector.

**Comment by GB756980** [comment]
`@echo off

title R3nzSkin or Sakura Injector

color 0A
MODE con: COLS=65 LINES=30
echo  ===============================
echo    R3nzSkin or Sakura Injector
echo    R3nzSkin 或 Sakura的注入器
echo  ===============================
echo.
echo 1、Inject R3nzSkin（注入R3nzSkin）
echo 2、Inject Sakura（注入Sakura）
echo.

REM 英雄联盟的Game路径
set LOL_game_path=D:\Game\WeGame\WeGameApps\英雄联盟\Game
REM R3nzSkin的dll文件路径
set R3nzSkin_dll_path=D:\Game\Game Tools\LOL\R3nzSkin\R3nzSkin.dll
REM Sakura的dll文件路径
set Sakura_dll_path=D:\Game\Game Tools\LOL\Sakura\Sakura.dll

goto query

REM 询问函数
:query
set var=""
set /p var="Select the dll you want to inject？（请选择您需要注入的dll？）"
goto choice

REM 选择函数
:choice
if "%var%"=="" (
	goto exit
) else (
	echo.%var%| findstr /R "^[0-9]*$" >nul
)

if %errorlevel% equ 0 (
	if "%var%"=="1" (
		goto Inject_R3nzSkin
	) else if "%var%"=="2" (
		goto Inject_Sakura
	) else (
		goto invalid_input
	)
) else (
	goto invalid_input
)

REM Inject R3nzSkin
:Inject_R3nzSkin
echo.
REM 删除 hid.dll 文件
del "%LOL_game_path%\hid.dll" /f /q
REM 复制文件并重命名为 hid.dll
copy "%R3nzSkin_dll_path%" "%LOL_game_path%\hid.dll"
echo R3nzSkin has been injected！（已注入R3nzSkin！）
echo.
pause
goto query

REM Inject Sakura
:Inject_Sakura
echo.
REM 删除 hid.dll 文件
del "%LOL_game_path%\hid.dll" /f /q
REM 复制文件并重命名为 hid.dll
copy "%Sakura_dll_path%" "%LOL_game_path%\hid.dll"
echo Sakura has been injected！（已注入Sakura！）
echo.
pause
goto query

:invalid_input
echo.
echo invalid input！（无效的输入！）
echo.
pause
goto query

:exit
exit`

**Comment by GB756980** [comment]
不过我有一个好想法，使用一个bat，将需要注入的dll，复制到Game目录中
However, I have a good idea to use a bat to copy the dll that needs to be injected into the Game directory

**Comment by GB756980** [comment]
不过我有一个好想法，使用一个bat，将需要注入的dll，复制到Game目录中

However, I have a good idea to use a bat to copy the dll that needs to be injected into the Game directory

**Comment by GB756980** [comment]
> 
![image](https://github.com/rumi-chan/Sakura/assets/58936114/d06aae2b-1910-46fe-a8fd-3511a6f744ef)
