### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by niscotg** [rumi-chan/Sakura#9]
the program worked for my first game, but then it crashed in the middle of it without doing anything special, just changing skins. and now it keeps crashing everytime i try to open it in game. i tried everything; opening it after entering the arene, before, before opening the game, everything; still crashes. is there anything i'm missing or doing wrong?

**Comment by niscotg** [comment]
{"currentComboSkinIndex":31,"curretSkinId":21,"fastExit":false,"fastExitKey":"F11","isFirstTime":false,"menuKey":"F1","nextSkinKey":"PAGE_UP","playerName":"","previousSkinKey":"PAGE_DOWN","quickSkinChange":false,"saveName":false}

hope this is it

**Comment by rumi-chan** [comment]
> {"currentComboSkinIndex":31,"curretSkinId":21,"fastExit":false,"fastExitKey":"F11","isFirstTime":false,"menuKey":"F1","nextSkinKey":"PAGE_UP","playerName":"","previousSkinKey":"PAGE_DOWN","quickSkinChange":false,"saveName":false}
> 
> hope this is it

There are some pet skins you can't change, idk why.
In your case is Nixie with skin 21: Socialite Nixie.
To solve the problem you just need to change the curretSkinId to 20, or delete the config file.
